version: '3.3'

services:
    nextjs:
        ports:
            - 3000:3000
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        env_file:
            - .env

    mongo:
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: byronwade
            MONGO_INITDB_ROOT_PASSWORD: byronwade
